add lighthouse

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,6 +30,24 @@ jobs:
       - run: bun i
       - run: bun run check
 
+  lighthouse:
+    if: github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: oven-sh/setup-bun@v2
+      - name: Install dependencies
+        run: bun i
+      - name: Build
+        run: bun run build
+      - name: run Lighthouse CI
+        run: |
+          bun x @lhci/cli@$LHCI_CLI_VERCSION autorun --collect.staticDistDir=$COLLECT_SATIC_DIST_DIR --collect.url=$URL || echo "Lighthouse CI failed!"
+        env:
+          LHCI_CLI_VERCSION: 0.14.0
+          COLLECT_SATIC_DIST_DIR: ${{ github.workspace }}/build
+          URL: https://ryoppippi.com
+
   # build-and-deploy:
   #   needs:
   #     - lint
